input: .
output: .retype
url: n1ghtmar3.com # Add your website here
branding:
  title: Juiced
  label: Setup Guide
poweredByRetype: true # Set to false to remove the Powered by Retype branding.
                      # A Retype Pro license is required.
                      # See: https://retype.com/pro
links:
  - text: Juiced Modding Discord
    link: https://discord.gg/pu2jdxR
footer:
  copyright: "&copy; Copyright N1GHTMAR3. All rights reserved."
